services:
  web-ui:
    image: flask-gunicorn:latest
    container_name: web-ui
    volumes:
      - ./Web_App:/app
    expose:
      - 8000
    networks:
      - app-net

  dmgen:
    image: flask-gunicorn:latest
    container_name: dmgen
    volumes:
      - ./XSIAM_DM_Generator:/app
    expose:
      - 8001
    command: ["gunicorn", "-w", "2", "-k", "gevent", "-b", "0.0.0.0:8001", "--timeout", "180", "app:app"]
    networks:
      - app-net

  spl:
    image: flask-gunicorn:latest
    container_name: spl
    volumes:
      - ./XSIAM_SPL_Converter:/app
    expose:
      - 8002
    command: ["gunicorn", "-w", "2", "-k", "gevent", "-b", "0.0.0.0:8002", "--timeout", "180", "app:app"]
    networks:
      - app-net

  ingestion-doc:
    image: flask-gunicorn:latest
    container_name: ingestion-doc
    volumes:
      - ./XSIAM_Ingestion_Document:/app
    expose:
      - 8003
    command: ["gunicorn", "-w", "2", "-k", "gevent", "-b", "0.0.0.0:8003", "--timeout", "180", "app:app"]
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web-ui
      - dmgen
      - spl
      - ingestion-doc
    networks:
      - app-net
  # nginx_certbot:
  #   image: nginx:alpine
  #   container_name: nginx_certbot
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx_cert_provision.conf:/etc/nginx/nginx.conf:ro
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   networks:
  #     - app-net

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: >
  #     sh -c "certbot certonly --webroot -w /var/www/certbot
  #           --email your@email.com
  #           --agree-tos
  #           --no-eff-email
  #           -d thedevguy.work -d www.thedevguy.work"
  #   networks:
  #     - app-net

  #toolbox:
  #  image: curlimages/curl:latest
  #  container_name: toolbox
  #  entrypoint: ["sleep", "infinity"]
  #  networks:
  #    - app-net
networks:
  app-net: